### ISSUE TITLE
Баг при попытке дописаться до разработчика

### ISSUE THREAD

**Issue by noteMASTER11** [yasinsky93/manual-react-app#3]
Добрый день, прошу исправить баг.

**Тестируемое окружение**: Интернет, Хабр Карьера
**Выполняемое действие**: попытка дописаться до старого школьного товарища и выразить ему респект за отчаянные попытки в IT, поделиться опытом, возможно, даже подсказать чего по работе.
**Ожидаемый результат**: "о, Дербень, сколько лет, сколько зим, я думал, что ты сдох давно!"

**Текущий результат**: обновил профиль Хабра месяц назад и даже не заходил проверить ЛС. А этот гит вообще на твою супругу, по ходу, прописан, потому что почта в коммитах не твоя.

**Comment by noteMASTER11** [comment]
Telegram: @mkzxt

**Comment by yasinsky93** [comment]
function getFriendContact(name){
     return frMap.get(name).cellphone
}

getFriendContact ('yasen') // 89002638502

чт, 16 сент. 2021 г., 14:06 Daniel Derbenev ***@***.***>:
